#!/usr/bin/env python3

import urllib.request
import time
import subprocess
try:
    import httplib  # python < 3.0
except:
    import http.client as httplib

def have_internet():
    conn = httplib.HTTPSConnection("google.com", timeout=5)
    try:
        conn.request("HEAD", "/")
        with open('/sys/class/gpio/gpio65/value', 'w') as f:
    	    f.write('1')

        return True
    except Exception:
        with open('/sys/class/gpio/gpio65/value', 'w') as f:
    	    f.write('0')
        return False
    finally:
        conn.close()

def connect(host='http://google.com'):
    try:
        urllib.request.urlopen(host) #Python 3.x
        return True
    except:
        return False
# 
try:
    rc = subprocess.call("/home/debian/Gokart_CAN_API/3G_sakis3g_mod/NET_CONNECT", shell=True)
except:
    
time.sleep(2)

while (have_internet()):
    time.sleep(10)	
