#!/bin/bash

FILE="/sys/class/gpio/gpio87/value"
LOG="/home/debian/"

while true
do
	if  grep -q 0 $FILE;
	then
		now=$(date +"%D %T")
		echo "$now: Power has been disabled. Shutting down!!!!" >> ${LOG}GoKartsystem.log
		shutdown now
	fi
	sleep 5
done
